config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: "dashboard#index", as: :user_root
  end

  # ---------- [ Static Pages ] ---------- #
  if ENABLE_LANDING_PAGES == true
    root to: "pages#show", id: "home"
    get "pages/*id" => "pages#show", :as => :page, :format => false
  else
    root to: "dashboard#index"
  end

  # ---------- [ Blog ] ---------- #
  if ENABLE_LANDING_PAGES == true && ENABLE_BLOG == true
    resources :blog, only: %i[index show], path: "blog"
    post "/contentful/webhook", to: "contentful#webhook"
  end

  # ---------- [ Devise ] ---------- #
  custom_controllers = {
    registrations: "registrations",
    confirmations: "confirmations",
    passwords: "passwords"
  }
  custom_controllers[:omniauth_callbacks] = "users/omniauth_callbacks" if ENABLE_GOOGLE_OAUTH
  devise_for :users, controllers: custom_controllers

  devise_scope :user do
    get :confirm_email, to: "confirmations#confirm_email", as: "confirm_email", path: "users/confirm-email"
    post :cancel_email_change, to: "registrations#cancel_email_change!", as: "cancel_email_change",
      path: "users/cancel-email-change"
  end

  # User Onboarding
  get "/onboarding", to: "onboarding#index", as: "onboarding"
  patch "/onboarding", to: "onboarding#update"

  # ---------- [ Main Routes ] ---------- #
  resources :dashboard, only: :index

  # ---------- [ Custom Error Pages ] ---------- #

  get "/404", to: "errors#not_found"
  get "/500", to: "errors#internal_server"
  get "/422", to: "errors#unprocessable_entity"

  # ---------- [ API Routes ] ---------- #
  draw :api if ENABLE_API == true || Rails.env.test?

  # ---------- [ Health Check ] ---------- #
  get "/up", to: "health_check#show"

  # ---------- [ Sitemap ] ---------- #
  if Rails.env.production?
    # Sitemap - redirect /sitemap.xml.gz to s3
    get "/sitemap.xml.gz" => redirect("#{SITEMAP_HOST}/sitemaps/sitemap.xml.gz")
  end

  # ---------- [ Gems ] ---------- #
  # Admin Panel
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Sidekiq
  if defined?(Sidekiq)
    require "sidekiq/web"

    authenticate :admin_user do
      mount Sidekiq::Web => "/sidekiq"
    end
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  include ContentfulHelper

  layout "application_landing_page"

  def index
    @page = (params[:page] || 1).to_i
    @posts = contentful_service.posts(@page)

    render_404! if @posts.empty?
  end

  def show
    @post = contentful_service.post(params[:id])
    render_404! if @post.nil?

    set_meta_tags(
      title: @post.title,
      description: @post.excerpt,
      article: {
        published_time: @post.published_at,
        modified_time: @post.updated_at
      }
    )
  end
end

app/views/blog/index.html.erb
<% title 'Blog' %>

<main class="max-w-2xl mx-auto px-4 pb-28">
  <header class="py-16 sm:text-center">
    <h1 class="h1 mb-3">Blog</h1>
    <p class="text-lg text-slate-700 dark:text-slate-400">
      All the latest news, straight from the team.
    </p>
  </header>

  <div class="sm:pb-12">
    <div class="space-y-6">
      <% @posts.each do |post| %>
        <article>
          <%= link_to blog_path(post.slug), class: 'card block hover:shadow-lg transition-shadow' do %>
            <% if post.featured_image %>
              <%= image_tag post.featured_image.url, class: 'h-48 sm:h-64 w-full object-cover' %>
            <% end %>

            <div class="card-body">
              <dl>
                <dt class="sr-only">Date</dt>
                <dd class="whitespace-nowrap text-sm leading-6 dark:text-slate-400">
                  <time datetime="<%= post.published_at.iso8601 %>">
                    <%= post.published_at.strftime('%B %d, %Y') %>
                  </time>
                </dd>
              </dl>

              <h3 class="h3 mt-3">
                <%= post.title %>
              </h3>

              <div class="mt-2 mb-4 prose-section line-clamp-2">
                <%= post.excerpt %>
              </div>

              <span class="text-primary font-medium">
                Read more &rarr;
              </span>
            </div>
          <% end %>
        </article>
      <% end %>
    </div>
  </div>


  <div class="flex justify-between items-center text-sm">
    <% if @page > 1 %>
      <%= link_to blog_index_path(page: @page - 1), class: "text-primary" do %>
        &larr; Previous Page
      <% end %>
    <% end %>

    <% if @posts.total > (@posts.limit * @page) %>
      <%= link_to blog_index_path(page: @page + 1), class: "text-primary" do %>
        Next Page &rarr;
      <% end %>
    <% end %>
  </div>

</main>

app/views/blog/show.html.erb
<div class="mb-40">
  <div class="max-w-8xl mx-auto">
    <div class="flex px-4 pt-8 pb-10 lg:px-8">
      <%= link_to blog_index_path, class: 'link text-sm font-medium' do %>
        &larr; Go back
      <% end %>
    </div>
  </div>
  <div class="px-4 sm:px-6 md:px-8">
    <div class="max-w-2xl mx-auto">
      <main>
        <article class="relative pt-10">
          <h1 class="h1"><%= @post.title %></h1>
          <div class="text-sm leading-6">
            <dl>
              <dt class="sr-only">Date</dt>
              <dd class="absolute top-0 inset-x-0 text-slate-700 dark:text-slate-400">
                <time datetime="<%= @post.published_at.iso8601 %>">
                  <%= @post.published_at.strftime('%A, %B %d, %Y') %>
                </time>
              </dd>
            </dl>
          </div>

          <% if @post.featured_image %>
            <div class="mt-6">
              <%= image_tag @post.featured_image.url, class: 'w-full object-cover rounded-2xl' %>
            </div>
          <% end %>

          <div class="mt-12 prose-section">
            <%= render_rich_text @post.content %>
          </div>
        </article>
      </main>
    </div>
  </div>
</div>